### ISSUE TITLE
Suggest adding standards publishers to the target audience of DPUB

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-charter#12]
OLD:
The mission of the Digital Publishing Interest Group is to provide a forum for experts in the digital publishing ecosystem of electronic journals, magazines, news, or book publishing (authors, creators, publishers, news organizations, booksellers, accessibility and internationalization specialists, etc.) for technical discussions towards a future vision of Digital Publishing.

PROPOSED:
The mission of the Digital Publishing Interest Group is to provide a forum for experts in the digital publishing ecosystem of electronic journals, magazines, news, standards, or book publishing (authors, creators, publishers, news organizations, booksellers, accessibility and internationalization specialists, etc.) for technical discussions towards a future vision of Digital Publishing.

**Comment by iherman** [comment]
Close by virtue of PR #14
