### ISSUE TITLE
Awkward intro sentence

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-charter#13]
OLD:
Whilst this Interest Group is not chartered to specify Recommendations, it will provide technical directions, identify technical issues and outline prototype solutions that relevant Working Groups of the W3C will have to finalize as final Web standards. 

PROPOSED:
While this Interest Group is not chartered to specify Recommendations, it will provide technical direction, identify technical issues, and outline prototype solutions for relevant Working Groups of the W3C to finalize as Web standards.

**Comment by iherman** [comment]
Close by virtue of PR #14
